#!/usr/bin/env python3
"""The district front doors: the project tables in each district's AGENTS.md, generated from the disk and the map so
they never go stale (Shaan, 24 Sep: "making sure there's not multiple front doors to the estate and the projects").

  doors.py            rewrite the tables between the `estate:doors` markers in every door listed in plan/doors.json
  doors.py --check    change nothing; exit 1 and name each door whose tables are out of date
  doors.py --commit   also commit each rewritten door in its own repo, when the generated block is the file's only
                      change, and push it when that commit is the only one the branch has that its upstream lacks
                      (doors in the map repo itself are committed by the umbrella snapshot)

A door's prose is hand-written; only the part between the markers is generated. One row per folder in each section:
what it is (plan/doors.json "what", else the folder's AGENTS.md "In one line", else its manifest.md, else its README),
its GitHub repo(s), and whether it is on this laptop or on GitHub only (with the command that brings it back).
"""
import json, os, re, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
WS = os.path.join(os.path.expanduser("~"), "SISO_Workspace")
BEGIN = "<!-- estate:doors begin: generated by SISO_Agents/siso-estate/tools/doors.py from the disk and plan/doors.json; edit those, not this table -->"
END = "<!-- estate:doors end -->"
QUIET = {".DS_Store", "manifest.md", "AGENTS.md", "CLAUDE.md", "README.md", ".gitkeep"}


def origin(path):
    r = subprocess.run(["git", "-C", path, "remote", "get-url", "origin"], capture_output=True, text=True)
    m = re.search(r"github\.com[:/]([^/]+/[^/]+?)(\.git)?$", r.stdout.strip())
    return m.group(1) if m else None


def repos_in(path, depth=3):
    """GitHub repos checked out at or under path (not inside another repo's own tree), nearest first."""
    if os.path.exists(os.path.join(path, ".git")):
        o = origin(path)
        return [o] if o else ["no remote"]
    out = []
    if depth == 0:
        return out
    try:
        kids = sorted(e for e in os.listdir(path) if not e.startswith(".") and e not in ("node_modules", "_intake"))
    except OSError:
        return out
    for k in kids:
        p = os.path.join(path, k)
        if os.path.isdir(p) and not os.path.islink(p):
            out += repos_in(p, depth - 1)
    return out


def first_line(path):
    """What a folder says it is, in one sentence."""
    for name in ("AGENTS.md", "manifest.md", "README.md"):
        f = os.path.join(path, name)
        if not os.path.isfile(f):
            continue
        text = open(f, errors="replace").read(6000)
        m = re.search(r"\*\*In one line:\*\*\s*(.+)", text)
        if m:
            line = m.group(1)
        else:
            body = re.sub(r"^---\n.*?\n---\n", "", text, flags=re.S)
            para, line = [], ""
            for ln in body.splitlines() + [""]:
                t = ln.strip()
                skip = t.startswith(("#", "|", ">", "<", "!", "```", "---", "- ", "* ")) or re.match(r"^\**[A-Za-z_ ]+:\**\s", t)
                if t and not skip:
                    para.append(t)
                elif para:
                    line = " ".join(para)
                    break
        line = re.split(r"\s+District:", line)[0]
        line = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", line).strip()
        if line:
            return sentence(line)
    return ""


def sentence(s, n=120):
    s = re.split(r"(?<=[A-Za-z0-9)])\.\s", s)[0].rstrip(".")
    return s if len(s) <= n else s[:n - 1].rsplit(" ", 1)[0] + "…"


def on_laptop(path):
    """True when the folder holds more than a stub (a manifest, an empty code/ folder)."""
    for root, dirs, files in os.walk(path):
        dirs[:] = [d for d in dirs if d != ".git"]
        if any(f not in QUIET and not os.path.islink(os.path.join(root, f)) for f in files) \
                or os.path.exists(os.path.join(root, ".git")):
            return True
    return False


GH = {}


def gh_description(repos):
    """GitHub's own description of the first sisodias repo in the row (machines/github/sisodias.json)."""
    if not GH:
        try:
            GH.update({r["nameWithOwner"].lower(): r.get("description") or "" for r in
                       json.load(open(os.path.join(REPO, "machines", "github", "sisodias.json")))})
        except (OSError, ValueError, KeyError):
            pass
    return next((sentence(GH[r.lower()]) for r in repos if GH.get(r.lower())), "")


def row(rel, cfg, placements, planes):
    path = os.path.join(WS, rel)
    what = cfg.get("what", {}).get(rel) or first_line(path)
    repos = cfg.get("repos", {}).get(rel) or [r for r in dict.fromkeys(repos_in(path)) if r]
    if not repos:
        repos = sorted({v["repo"] for k, v in placements.items() if k == rel or k.startswith(rel + "/")},
                       key=lambda r: (not r.lower().startswith("sisodias/"), r.lower()))
    if not what or len(what) < 25:
        what = gh_description(repos) or what
    note = cfg.get("repo_note", {})
    shown = ", ".join(f"{r} ({note[r]})" if r in note else r for r in repos[:4]) + (f" +{len(repos) - 4}" if len(repos) > 4 else "")
    if on_laptop(path):
        state = "here"
        plane = next((p for p, paths in planes.items() if any(q == rel or q.startswith(rel + "/") for q in paths)), None)
        if not repos and plane:
            shown, state = "no repo", f"here; files in the encrypted plane `{plane}`"
    else:
        plane = next((p for p, paths in planes.items() if any(q == rel or q.startswith(rel + "/") for q in paths)), None)
        if repos:
            state = f"GitHub only: `estate restore --only {rel} --run`"
        elif plane:
            shown, state = "no repo", f"off the laptop: files in the encrypted plane `{plane}`"
        else:
            state = "empty"
    name = rel.split("/", 1)[1] if "/" in rel else rel
    return f"| `{name}/` | {what or '—'} | {shown or '—'} | {state} |"


def build(door, cfg, placements, planes):
    out = []
    for sec in cfg["sections"]:
        base = os.path.join(WS, sec["dir"])
        rels = [os.path.join(sec["dir"], r) for r in sec["rows"]] if "rows" in sec else [
            os.path.join(sec["dir"], k) for k in sorted(os.listdir(base), key=str.lower)
            if os.path.isdir(os.path.join(base, k)) and not k.startswith((".", "_")) and not os.path.islink(os.path.join(base, k))
            and k not in sec.get("skip", [])]
        out += [f"### {sec['title']}", "", sec["intro"], "", "| Folder | What it is | Repo | On this laptop |", "|---|---|---|---|"]
        out += [row(r, cfg, placements, planes) for r in rels if os.path.isdir(os.path.join(WS, r))]
        out.append("")
    return "\n".join([BEGIN, ""] + out + [END])


def sync_manifest(m, mcfg):
    """Keep a district manifest's `works` equal to the repos on disk: existing entries keep their hand-written fields,
    new repos get their one-line description, entries whose folder is gone are dropped."""
    root = os.path.join(WS, mcfg["root"])
    have = {w["path"]: w for w in m.get("works", [])}
    works = []
    for sub in mcfg["scan"]:
        base = os.path.join(root, sub)
        for k in sorted(os.listdir(base), key=str.lower):
            p = os.path.join(base, k)
            rel = os.path.join(sub, k) if sub else k
            if k.startswith((".", "_")) or k in mcfg.get("skip", []) or os.path.islink(p) or not os.path.isdir(os.path.join(p, ".git")):
                continue
            o = origin(p)
            if not o:
                continue
            w = dict(have.get(rel) or {"name": k, "path": rel, "responsibility": first_line(p) or k})
            w["remote"] = re.sub(r"://[^/@]+@", "://", subprocess.run(["git", "-C", p, "remote", "get-url", "origin"],
                                                                  capture_output=True, text=True).stdout.strip())
            works.append(w)
    m["works"] = works
    m["generated_at"] = time.strftime("%Y-%m-%d")
    m["generated_by"] = "SISO_Agents/siso-estate/tools/doors.py (works = the repos on disk; hand-written fields kept)"
    return m


def commit_door(f):
    """Commit a door whose only change is its generated block; push when nothing else is waiting. Returns a note."""
    top = subprocess.run(["git", "-C", os.path.dirname(f), "rev-parse", "--show-toplevel"], capture_output=True, text=True).stdout.strip()
    if not top or os.path.realpath(top) == os.path.realpath(WS):
        return "left for the umbrella snapshot"
    rel = os.path.relpath(f, top)
    g = lambda *a: subprocess.run(["git", "-C", top, *a], capture_output=True, text=True)
    head = g("show", f"HEAD:{rel}")
    new = open(f).read()
    if head.returncode == 0 and BEGIN in head.stdout and END in head.stdout:
        h = head.stdout
        if h[:h.index(BEGIN)] + new[new.index(BEGIN):new.index(END) + len(END)] + h[h.index(END) + len(END):] != new:
            return "not committed: the door also has hand edits outside the generated block"
    if g("diff", "--cached", "--quiet", "--", rel).returncode != 0:
        return "not committed: something else is staged for it"
    c = g("commit", "-q", "-m", f"{rel}: regenerate the folder tables (siso-estate tools/doors.py)", "--", rel)
    if c.returncode != 0:
        return "commit failed: " + (c.stderr or c.stdout)[-120:]
    ahead = g("rev-list", "--count", "@{u}..HEAD")
    if ahead.returncode == 0 and ahead.stdout.strip() == "1" and g("push", "-q").returncode == 0:
        return "committed and pushed"
    return "committed (not pushed: the branch has other unpushed commits or no upstream)"


def main():
    check = "--check" in sys.argv
    commit = "--commit" in sys.argv
    cfg = json.load(open(os.path.join(REPO, "plan", "doors.json")))
    placements = json.load(open(os.path.join(REPO, "plan", "github-placements.json")))["placements"]
    planes = {p["name"]: [q.rstrip("/") for q in p.get("paths", [])]
              for p in json.load(open(os.path.join(REPO, "plan", "data-planes.json"))).get("planes", [])}
    stale = []
    for door, dcfg in cfg["doors"].items():
        f = os.path.join(WS, door)
        if not os.path.isfile(f):
            stale.append(f"{door}: missing (no such file)")
            continue
        text = open(f).read()
        if BEGIN not in text or END not in text:
            stale.append(f"{door}: no estate:doors markers")
            continue
        new = text[:text.index(BEGIN)] + build(door, dict(dcfg, what=cfg.get("what", {}), repos=cfg.get("repos", {}), repo_note=cfg.get("repo_note", {})),
                                               placements, planes) + text[text.index(END) + len(END):]
        if new != text:
            stale.append(door)
            if not check:
                open(f, "w").write(new)
                if commit:
                    print(f"  {door}: {commit_door(f)}")
    for mf, mcfg in cfg.get("manifests", {}).items():
        f = os.path.join(WS, mf)
        if not os.path.isfile(f):
            continue
        text = open(f).read()
        new = sync_manifest(json.loads(text), mcfg)
        body = json.dumps(new, indent=2, ensure_ascii=False) + ("\n" if text.endswith("\n") else "")
        if json.loads(body)["works"] != json.loads(text)["works"]:
            stale.append(mf)
            if not check:
                open(f, "w").write(body)
    for s in stale:
        print(("stale: " if check or ":" in s else "rewrote: ") + s)
    sys.exit(1 if check and stale else 0)


if __name__ == "__main__":
    main()
