#!/usr/bin/env python3
"""The generated top of every repo's door (GOAL A8 "Beautiful"): one block, from one template, right under the header
line fix.py already writes (`# name` + `**In one line:**`). Where it sits, its owner, how to run it, where to write,
worktrees and the `estate where` rule, filled from the disk, machines/<m>/code.json and plan/owners.json.

  door_top.py            dry run: which live repo gets a block, which is skipped and why; prints one sample
  door_top.py --run      write the block (between the estate:door markers) and commit AGENTS.md alone, path-limited,
                         pushed only when it is the branch's one unpushed commit and the secret scan is clean
  door_top.py --check    exit 1 when a written block is out of date; prints the live doors still missing the block
  door_top.py --dirty    also put the block in the working copy of a door that holds someone's uncommitted edits (or
                         a repo with something else staged): their lines are kept, nothing is staged or committed;
                         it goes in with the owner's next commit of AGENTS.md

Live = our own building (code.json owner `own`), lifecycle active or warm, not on fix-policies' never list, not a
submodule checkout. Written only where AGENTS.md is clean (`git diff --quiet -- AGENTS.md`, nothing staged) and no
working herdr agent stands in the repo. Everything below the block is the owner's and is never touched.
"""
import argparse, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
WS = os.path.join(os.path.expanduser("~"), "SISO_Workspace")
sys.path.insert(0, HERE)
import fix  # noqa: E402  the same skip rules, owners, commit+scan+push and receipts the fix policies use

TEMPLATE = os.path.join(REPO, "plan", "door-template.md")
BEGIN = "<!-- estate:door begin: generated by SISO_Agents/siso-estate/tools/door_top.py from plan/door-template.md; edit those, not this block -->"
END = "<!-- estate:door end -->"
BLOCK = re.compile(re.escape(BEGIN.split(":", 1)[0]) + r":door begin[^\n]*-->\n.*?" + re.escape(END) + r"\n?", re.S)
HEADER = re.compile(r"^\*\*In one line:\*\*.*?(?:\n\s*\n|\Z)", re.S | re.M)


def template_rows():
    return [ln for ln in open(TEMPLATE).read().splitlines() if ln.startswith("|")]


def run_line(top):
    """How to run it: the entry points the repo itself declares."""
    out = []
    pj = os.path.join(top, "package.json")
    if os.path.isfile(pj):
        try:
            scripts = json.load(open(pj)).get("scripts", {}) or {}
        except ValueError:
            scripts = {}
        pm = "pnpm" if os.path.exists(os.path.join(top, "pnpm-lock.yaml")) else \
             "bun" if any(os.path.exists(os.path.join(top, f)) for f in ("bun.lockb", "bun.lock")) else "npm"
        out += [f"`{pm} run {s}`" for s in ("dev", "start", "build", "test") if s in scripts][:3]
    if os.path.isfile(os.path.join(top, "Makefile")):
        out.append("`make` (see `Makefile`)")
    if os.path.isfile(os.path.join(top, "pyproject.toml")):
        out.append("Python project (`pyproject.toml`)")
    if os.path.isdir(os.path.join(top, "bin")) and not os.path.islink(os.path.join(top, "bin")):
        out.append("commands in `bin/`")
    if os.path.isfile(os.path.join(top, "docker-compose.yml")):
        out.append("`docker compose up` (`docker-compose.yml`)")
    if not out:
        out.append("no entry point declared; see `README.md`" if os.path.isfile(os.path.join(top, "README.md"))
                   else "no entry point declared")
    return " · ".join(out)


def write_line(top):
    out = []
    for rel, what in ((".agents/HANDOFF.md", "state"), (".agents/memory/MEMORY.md", "durable facts, one file each plus an index line"),
                      (".agents/source", "Shaan's words, verbatim")):
        if os.path.exists(os.path.join(top, rel)):
            out.append(f"`{rel}` ({what})")
    return "; ".join(out) or ".agents/ is this repo's one agent folder (ADR 0015); create what you need there"


def github(x):
    m = re.search(r"github\.com[:/]([^/]+/[^/]+?)(\.git)?/?$", x.get("origin") or "")
    return m.group(1) if m else "no remote yet (`estate backup plan` houses it)"


def owner(x):
    seat = x.get("seat", "")
    who = fix.OWNERS["seats"].get(seat, seat) or "not yet assigned"
    return f"not yet assigned; {who} holds it" if x.get("state_land") else who


def block(x):
    top = os.path.join(WS, x["path"])
    f = {"path": x["path"], "district": x["district"], "github": github(x), "owner": owner(x),
         "run": run_line(top), "write": write_line(top), "name": os.path.basename(top)}
    rows = [r.format(**f) for r in template_rows() if all(f.get(k) for k in re.findall(r"\{(\w+)\}", r))]
    return BEGIN + "\n" + "\n".join(rows) + "\n" + END + "\n"


def render(text, blk, x=None):
    """The door with the block in place: replaced if present, else inserted right after the header paragraph. A
    hand-written door with a `# title` first line but no header gets fix.py's one-line header and the block right
    under the title: an insertion only, every line of the owner's kept."""
    if BLOCK.search(text):
        return BLOCK.sub(lambda _: blk, text, count=1)
    m = HEADER.search(text)
    if not m and x and text.startswith("# "):
        one = next((ln for ln in fix.door_text(x).splitlines() if ln.startswith("**In one line:**")), "")
        title, _, rest = text.partition("\n")
        return title + "\n\n" + one + "\n\n" + blk + "\n" + rest.lstrip("\n") if one else None
    if not m:
        return None
    head = text[:m.end()].rstrip("\n") + "\n\n"
    return head + blk + "\n" + text[m.end():].lstrip("\n")


def live(x):
    if x["owner"] != "own" or x.get("lifecycle") not in ("active", "warm") or x["path"] == ".":
        return False
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--machine", default=os.environ.get("ESTATE_MACHINE", "laptop"))
    ap.add_argument("--dirty", action="store_true")
    ap.add_argument("--only", default="")
    a = ap.parse_args()
    code = json.load(open(os.path.join(REPO, "machines", a.machine, "code.json")))
    busy = fix.working_agents()
    counts, stale, sample = {"live": 0, "current": 0, "write": 0, "written": 0, "skip": 0, "working_copy": 0, "missing": 0}, [], None
    missing = []
    for x in code["results"]:
        if not live(x) or (a.only and a.only not in x["path"]):
            continue
        counts["live"] += 1
        top = os.path.join(WS, x["path"])
        door = os.path.join(top, "AGENTS.md")
        why = "not on this disk" if not os.path.isdir(top) else fix.skip_reason(x, busy)
        if not why and not os.path.isfile(door):
            why = "no AGENTS.md (the door policy writes one first)"
        text = open(door, errors="replace").read() if os.path.isfile(door) else ""
        new = render(text, block(x), x) if text else None
        if not why and new is None:
            why = "no `**In one line:**` header to sit under"
        if not why and fix.git(top, "diff", "--quiet", "--", "AGENTS.md").returncode:
            why = "AGENTS.md has someone's uncommitted change"
        if not why and fix.git(top, "ls-files", "--error-unmatch", "AGENTS.md").returncode:
            why = "AGENTS.md is not tracked here (the owner's choice)"
        if new == text:
            counts["current"] += 1
            continue
        if a.check and BLOCK.search(text):
            stale.append(x["path"])
        if not BLOCK.search(text) and not why.startswith(("never:", "not our house", "a submodule", "not on this disk")):
            counts["missing"] += 1
            missing.append(x["path"])
        dirty = why in ("AGENTS.md has someone's uncommitted change", "something is already staged") and new
        if a.dirty and a.run and dirty and not fix.git(top, "diff", "--cached", "--quiet", "--", "AGENTS.md").returncode:
            # their lines, in their order, with only the block added: nothing of theirs is rewritten
            ours = lambda t: [ln for ln in BLOCK.sub("", t).splitlines() if ln.strip() and not (ln.startswith("**In one line:**") and ln not in text)]
            if ours(new) == ours(text):
                with open(door + ".estate-tmp", "w") as fh:
                    fh.write(new)
                os.replace(door + ".estate-tmp", door)
                counts["working_copy"] += 1
                if x["path"] in missing:             # an out-of-date block was never counted missing
                    missing.remove(x["path"])
                counts["missing"] = len(missing)
                print(f"wcopy {x['path']}  [{why}; block in the working copy only, not staged or committed]")
                continue
        if why:
            counts["skip"] += 1
            print(f"skip  {x['path']}  [{why}]")
            continue
        counts["write"] += 1
        sample = sample or (x["path"], new)
        print(f"door  {x['path']}")
        if not a.run:
            continue
        if top == REPO:                          # this house: written here, committed with the lane's own files under the lock
            with open(door + ".estate-tmp", "w") as fh:
                fh.write(new)
            os.replace(door + ".estate-tmp", door)
            print("      written; commit it with estate-lock")
            continue
        with open(door + ".estate-tmp", "w") as fh:
            fh.write(new)
        os.replace(door + ".estate-tmp", door)
        fix.git(top, "add", "--", "AGENTS.md")
        sha, pushed, note = fix.commit(top, ["AGENTS.md"], "AGENTS.md: the door's generated top (where, owner, run, write)", "door-top")
        fix.receipt(a.machine, x["path"], "door-top", sha, pushed, note)
        counts["written"] += 1 if sha else 0
        print(f"      {sha or 'not committed'}; {'pushed' if pushed else 'not pushed'}" + (f" ({note})" if note else ""))
    print(json.dumps(counts))
    if sample and not a.run:
        print(f"\n--- sample: {sample[0]}/AGENTS.md (top 30 lines) ---")
        print("\n".join(sample[1].splitlines()[:30]))
    if a.check and missing:
        print("missing the block: " + ", ".join(missing))
    if a.check and stale:
        print("out of date: " + ", ".join(stale))
        sys.exit(1)


if __name__ == "__main__":
    main()
