#!/usr/bin/env python3
"""The estate's history (docs/PLANNER.md phase 2), from the records only: where the laptop started (each goal check's
baseline), what changed each day (the record lines in machines/<m>/*.jsonl and this repo's commits), which plans were
written and where each stands, and where it is now. Run: python3 tools/history.py -> docs/HISTORY.md"""
import collections, json, pathlib, subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
M = ROOT / "machines/laptop"
RECORDS = {"moves": "moved", "removed": "removed with proof", "retired": "retired off the laptop", "houses": "housed or synced",
           "repoints": "repointed", "fixes": "routine fixes (the law)", "intake": "loose files filed", "retired-links": "compat links retired"}
# the plans, and where each stands (hand-kept: a plan's status is a judgement, not a count)
PLANS = [("docs/MODEL.md", "the estate model: islands, compounds, postcodes", "superseded in part: its §1 and §4 by the legend"),
         (".agents/EXECUTION-QUEUE.md", "the execution queue", "jobs 1-11 done 23 Sep; 'Now' holds the partner moves"),
         ("plan/GOAL.md", "the unfuck goal, 16 checks", "3 of 16 met; A13 dropped"),
         ("plan/goal-2050.json", "Shanghai 2050: 10 pillars", "first move landed (building code, operations centre)"),
         ("docs/LEGEND.md", "the legend: the estate mirrors the business", "agreed 25 Sep; the code knows partners; no move run yet"),
         ("docs/MERGES.md", "which repos to merge, and the vault", "proposed; nothing merged"),
         ("docs/PLANNER.md", "the state-planner run", "running: cards, edges, this history"),
         ("docs/SCORE.md", "the score and the eras", "generated nightly")]


def day(t):
    t = str(t)
    return f"{t[:4]}-{t[4:6]}-{t[6:8]}" if len(t) >= 8 and t[:8].isdigit() else t[:10]


def main():
    per = collections.defaultdict(collections.Counter)
    for f, what in RECORDS.items():
        p = M / f"{f}.jsonl"
        for l in (p.read_text().splitlines() if p.exists() else []):
            if l.strip():
                per[day(json.loads(l).get("at", ""))][what] += 1
    log = subprocess.run(["git", "log", "--format=%ad\t%s", "--date=format:%Y-%m-%d"], cwd=ROOT, capture_output=True, text=True).stdout
    commits = collections.defaultdict(list)
    for l in log.splitlines():
        d, s = l.split("\t", 1)
        commits[d].append(s)
    born = {}
    for p, *_ in PLANS:
        r = subprocess.run(["git", "log", "--diff-filter=A", "--format=%ad", "--date=format:%d %b", "--", p], cwd=ROOT, capture_output=True, text=True).stdout.split()
        born[p] = " ".join(r[-2:]) if r else "?"
    goal = json.loads((ROOT / "plan/goal.json").read_text())

    L = ["# Estate history", "", "Generated by `tools/history.py` from the record lines in `machines/laptop/` and this repo's git log. "
         "Counts are record lines, not judgements.", "", "## 1. Where the laptop started, and where it is", "",
         "| Check | On 22 Sep | Now |", "|---|---|---|"]
    for c in goal["done_when"]:
        now = c.get("now", "").split(" (measured")[0]
        L.append(f"| {c['id']} {c['name']} | {c.get('baseline', '')} | {now[:220]}{'...' if len(now) > 220 else ''} |")
    L += ["", "## 2. Day by day", ""]
    for d in sorted(set(per) | {d for d in commits if d >= "2026-09-22"}):
        if d < "2026-09-22":
            continue
        work = ", ".join(f"{n} {w}" for w, n in per[d].most_common())
        L += [f"**{d}**: {len(commits.get(d, []))} estate commits. {work or 'no record lines'}.", ""]
        L += ["The day's last six commits:"] + [f"- {s[:160]}" for s in commits.get(d, [])[:6][::-1]] + [""]
    L += ["## 3. The plans", "", "| Plan | What | Written | Where it stands |", "|---|---|---|---|"]
    L += [f"| `{p}` | {w} | {born[p]} | {s} |" for p, w, s in PLANS]
    (ROOT / "docs/HISTORY.md").write_text("\n".join(L) + "\n")
    print("wrote docs/HISTORY.md")


if __name__ == "__main__":
    main()
