#!/usr/bin/env python3
"""The whole laptop as one generated map: docs/operations/LAPTOP-MAP.md in the map repo (~/SISO_Workspace).

  laptop-map.py [--machine laptop] [--check]

Sections: the workspace's districts (plan/layout.json, the root AGENTS.md table, repos per district), the home folder by
zone (plan/home-zones.json; anything in ~ that is not listed is flagged), the agent homes with their last write, the
hidden folders inside the workspace (machines/<m>/dots.json, ADR 0015), SISO's launchd services and whether each one's
program exists, where keys live, and the machines on the map. --check exits 1 when the file on disk is out of date.
"""
import argparse, collections, json, os, plistlib, re, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
HOME = os.path.expanduser("~")
WS = os.path.join(HOME, "SISO_Workspace")
OUT = os.path.join(WS, "docs", "operations", "LAPTOP-MAP.md")


def load(p, default=None):
    try:
        return json.load(open(p))
    except (OSError, ValueError):
        return default


def ago(t):
    d = (time.time() - t) / 86400
    return "today" if d < 1 else f"{int(d)} days ago"


def build(machine):
    zones = load(os.path.join(REPO, "plan", "home-zones.json"), {"zones": {}})["zones"]
    repos = load(os.path.join(REPO, "machines", machine, "repos.json"), {"repos": []})["repos"]
    dots = load(os.path.join(REPO, "machines", machine, "dots.json"), {})
    machines = load(os.path.join(REPO, "plan", "machines.json"), {})
    planes = load(os.path.join(REPO, "plan", "data-planes.json"), {"planes": []})["planes"]
    root_md = open(os.path.join(WS, "AGENTS.md")).read()
    L = ["# The laptop", "",
         "Generated by `SISO_Agents/siso-estate/tools/laptop-map.py` from the disk and the estate's plan files; `estate refresh`",
         "and the nightly rewrite it. Do not edit it by hand: change `plan/home-zones.json`, `plan/layout.json` or the thing itself.",
         "", "Find anything: `estate where <words>`. The workspace's own map is `~/SISO_Workspace/AGENTS.md`.", ""]

    # 1. the workspace
    L += ["## ~/SISO_Workspace: the districts", "", "| District | Repos checked out here | Door |", "|---|---|---|"]
    ws_repos = [r for r in repos if str(r.get("path", "")).startswith(WS + "/") and r.get("kind") != "worktree"]
    for m in re.finditer(r"^\| `([^`/]+)/` \|", root_md, re.M):
        d = m.group(1)
        n = sum(1 for r in ws_repos if str(r["path"]).startswith(f"{WS}/{d}/") or str(r["path"]) == f"{WS}/{d}")
        door = next((f for f in ("AGENTS.md", "DOMAIN-MAP.md") if os.path.exists(os.path.join(WS, d, f))), "")
        L.append(f"| `{d}/` | {n} | {'`' + d + '/' + door + '`' if door else '—'} |")
    L.append("")

    # 2. the home folder by zone
    listed = {e: z for z, v in zones.items() for e in v["entries"]}
    here = sorted(os.listdir(HOME), key=str.lower)
    L += ["## ~ (the home folder), by zone", "", "| Zone | What it is | Entries |", "|---|---|---|"]
    for z, v in zones.items():
        es = [e for e in v["entries"] if e in here]
        notes = v.get("notes", {})
        L.append(f"| {z} | {v['why']} | " + ", ".join(f"`{e}`" + (f" ({notes[e]})" if e in notes else "") for e in es) + " |")
    stray = [e for e in here if e not in listed]
    gone = [e for z, v in zones.items() for e in v["entries"] if e not in here]
    L += ["", f"**Not in the zone table ({len(stray)}):** " + (", ".join(f"`{e}`" for e in stray) if stray else "none") +
          ". A new entry here is a stray until `plan/home-zones.json` gives it a zone.", ""]
    if gone:
        L += [f"Listed but no longer in ~: {', '.join(f'`{e}`' for e in gone)}.", ""]

    # 3. agent homes
    ah = zones.get("agent homes", {})
    live = set(ah.get("live", []))
    L += ["## Agent homes", "", "One home per harness (goal A12). Last write is the newest change directly inside the folder.", "",
          "| Home | Live | Last write |", "|---|---|---|"]
    for e in ah.get("entries", []):
        p = os.path.join(HOME, e)
        if not os.path.exists(p):
            continue
        t = max([os.path.getmtime(p)] + ([os.path.getmtime(os.path.join(p, x)) for x in os.listdir(p)[:500]] if os.path.isdir(p) else []))
        L.append(f"| `~/{e}` | {'yes' if e in live else 'no'} | {ago(t)} |")
    L.append("")

    # 4. hidden folders inside the workspace
    if dots:
        f = dots.get("findings", {})
        L += ["## Hidden folders inside the workspace", "",
              f"{dots.get('total', 0)} hidden folders (`machines/{machine}/dots.json`, {dots.get('at', '')[:16]}), against "
              "`SISO_Agents/siso-estate/docs/adr/0015-the-hidden-estate.md`: every repo has one agent folder, `.agents/`; "
              "harness folders hold config only; tool state is never tracked.", "",
              "| Class | Count |", "|---|---|"] + [f"| {k} | {v} |" for k, v in dots.get("by_class", {}).items()] + [""]
        for k, v in f.items():
            if k == "unknown":
                continue
            L.append(f"- **{k}: {len(v)}**" + (": " + ", ".join(f"`{x['path']}`" for x in v[:6]) + (" ..." if len(v) > 6 else "") if v else ""))
        L.append("")

    # 5. services
    L += ["## SISO's services (launchd)", "", "| Label | Loaded | Runs | Program exists |", "|---|---|---|---|"]
    loaded = {l.split("\t")[-1] for l in subprocess.run(["launchctl", "list"], capture_output=True, text=True).stdout.splitlines()}
    la = os.path.join(HOME, "Library", "LaunchAgents")
    for fn in sorted(os.listdir(la)):
        if not fn.startswith("com.siso.") or not fn.endswith(".plist"):
            continue
        try:
            pl = plistlib.load(open(os.path.join(la, fn), "rb"))
        except Exception:
            L.append(f"| `{fn}` | ? | unreadable plist | ? |")
            continue
        label = pl.get("Label", fn[:-6])
        args = pl.get("ProgramArguments") or [pl.get("Program", "")]
        if len(args) >= 3 and os.path.basename(args[0]) in ("bash", "zsh", "sh") and args[1] in ("-c", "-lc"):
            cmd = args[2].replace("~", HOME)
            prog = next((t for t in re.findall(r"(/[^\s;&|]+)", cmd) if not t.startswith(("/bin/", "/usr/bin/"))), args[2])
        else:
            prog = next((a for a in args if a.startswith(("/", "~")) and not a.startswith(("/bin/", "/usr/bin/", "/opt/homebrew/bin/"))), args[0] if args else "")
        exists = bool(prog) and (os.path.exists(os.path.expanduser(prog)) or os.path.exists(os.path.expanduser(prog.split()[0])))
        L.append(f"| `{label}` | {'yes' if label in loaded else 'no'} | "
                 f"`{prog.replace(HOME, '~')[:90]}` | {'yes' if exists else '**no**'} |")
    L.append("")

    # 6. keys and machines
    L += ["## Keys", "", "- Project keys: `~/SISO_Workspace/.credentials/projects/<map path>/` (backed up encrypted: plane `credentials`); "
          "`estate restore` puts them back with their repo. `houses.py keys <repo>` files a new one.",
          f"- Encrypted data planes: {len(planes)} (`SISO_Agents/siso-estate/plan/data-planes.json`).",
          "- Where every other credential lives: the `siso-credentials` skill.", "",
          "## Machines on the map", "", "| Machine | Status |", "|---|---|"]
    for name, m in (machines.get("machines") or machines).items():
        if isinstance(m, dict):
            L.append(f"| {name} | {str(m.get('status') or m.get('why') or '')[:110]} |")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--machine", default=os.environ.get("ESTATE_MACHINE", "laptop"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    new = build(a.machine)
    old = open(OUT).read() if os.path.exists(OUT) else ""
    strip = lambda s: re.sub(r"\| (today|\d+ days ago) \|", "|", s)   # ages move every day; they are not drift
    if a.check:
        print("fresh" if strip(new) == strip(old) else "stale: docs/operations/LAPTOP-MAP.md")
        sys.exit(0 if strip(new) == strip(old) else 1)
    if new != old:
        open(OUT, "w").write(new)
        print("rewrote docs/operations/LAPTOP-MAP.md")


if __name__ == "__main__":
    main()
