#!/usr/bin/env python3
"""Keep the Great Library's private placement overlay in step with this machine's repositories.

  overlay-sync.py plan|run [--machine laptop]

The overlay (Great_Library_of_SISO/.local/private-registry/overlay.json, schema
schemas/private-source-overlay.schema.json) is THE machine registry: public Library identities -> paths here. This adds
an entry for every live repository and lane in machines/<machine>/repos.json that has none (matched by path), refreshes
expected_remote on generated entries, and drops entries whose path no longer exists (listed in the output). A repository whose `git status` fails is left out
and reported, since the Library's estate status walks every entry. Hand-written
entries are otherwise kept as they are. New entries point at the laptop estate source inventory until a Work claims
them; `estate where` and `gls` then see the same places.
"""
import json, os, re, subprocess, sys, time

HOME = os.path.expanduser("~")
WS = os.path.join(HOME, "SISO_Workspace")
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OVERLAY = os.path.join(WS, "Great_Library_of_SISO", ".local", "private-registry", "overlay.json")
INVENTORY_ID = "gls:source-inventory:7c9e2a41-5d68-4f03-b8a7-1e6c9d2f405b"
GEN = "generated by siso-estate tools/overlay-sync.py from machines/laptop/repos.json"
SKIP = re.compile(r"/(_archive|node_modules|\.lake|\.treehouse)/|/\.worktrees/|/\.claude/worktrees/|/\.codex/worktrees/|"
                  r"/runtime/|/releases/|/upstream/|/vendor/|/\.local/|/\.teable-runtime")


def slug(rel):
    return re.sub(r"[^a-z0-9]+", "-", rel.lower()).strip("-")[:120].strip("-")


def visibility(gh, gh_vis):
    if not gh:
        return "private"
    owner = gh.get("owner", "").lower()
    if owner not in ("sisodias", "lordsisodia"):
        return "public"
    return "public" if gh_vis.get(f"{owner}/{gh.get('repo', '')}".lower()) == "PUBLIC" else "private"


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "plan"
    machine = sys.argv[sys.argv.index("--machine") + 1] if "--machine" in sys.argv else os.environ.get("ESTATE_MACHINE", "laptop")
    inv = json.load(open(os.path.join(REPO, "machines", machine, "repos.json")))["repos"]
    gh_vis = {}
    for owner in ("sisodias", "Lordsisodia"):
        ghp = os.path.join(REPO, "machines", "github", owner + ".json")
        if os.path.exists(ghp):
            try:
                d = json.load(open(ghp))
            except ValueError:
                continue
            for r in (d if isinstance(d, list) else d.get("repos", [])):
                name = r.get("nameWithOwner") or f"{owner}/{r.get('name', '')}"
                gh_vis[name.lower()] = (r.get("visibility") or ("PRIVATE" if r.get("isPrivate") else "PUBLIC")).upper()
    ov = json.load(open(OVERLAY))
    by_path = {e["path"]: e for e in ov["entries"]}
    ids = {e["entry_id"] for e in ov["entries"]}
    gone = [e for e in ov["entries"] if not os.path.exists(e["path"])]
    added = []
    for r in inv:
        p = r["path"]
        if not p.startswith(WS + "/") or SKIP.search(p + "/") or not os.path.isdir(p):
            continue
        kind = "worktree" if r["kind"] == "worktree" else "canonical_repo" if r["kind"] == "repo" else None
        if not kind:
            continue
        gh = (r.get("github") or [{}])[0]
        remote = (r.get("remotes") or {}).get("origin")
        remote = re.sub(r"//[^/@]+@", "//", remote) if remote else None
        rel = os.path.relpath(p, WS)
        if p in by_path:
            e = by_path[p]
            if e.get("notes", "").startswith(GEN) and remote:
                e["expected_remote"] = remote
            continue
        st = subprocess.run(["git", "-C", p, "status", "--porcelain", "-uno"], capture_output=True, text=True, timeout=120)
        if st.returncode:
            print(f"  skip (git status fails): {rel}: {st.stderr.strip().splitlines()[-1][:100] if st.stderr.strip() else ''}")
            continue
        eid = "gls:private-entry:" + slug(rel)
        while eid in ids:
            eid += "-x"
        ids.add(eid)
        e = {"entry_id": eid, "registry_record_id": INVENTORY_ID, "unit_kind": kind, "path": p,
             "expected_visibility": visibility(gh, gh_vis), "storage_class": "tracked_source",
             "notes": GEN + (f"; third-party clone of {gh.get('owner')}/{gh.get('repo')}" if gh and gh.get("owner", "").lower()
                             not in ("sisodias", "lordsisodia") else "")}
        if remote:
            e["expected_remote"] = remote
        added.append(e)
    print(f"overlay: {len(ov['entries'])} entries; +{len(added)} new; -{len(gone)} whose path is gone")
    for e in gone:
        print(f"  gone: {e['entry_id']}  {e['path'].replace(HOME, '~')}")
    if cmd != "run":
        for e in added[:15]:
            print(f"  new: {e['entry_id']}  {e['unit_kind']}  {e['expected_visibility']}")
        return
    def healthy(e):
        """A generated entry holds only while its path is the top of its own work tree: an emptied folder inside another
        repo (a removed submodule checkout) passes `git status` through its parent, so status alone is not enough."""
        if not e.get("notes", "").startswith(GEN):
            return True
        top = subprocess.run(["git", "-C", e["path"], "rev-parse", "--show-toplevel"], capture_output=True, text=True)
        if top.returncode or os.path.realpath(top.stdout.strip()) != os.path.realpath(e["path"]):
            return False
        return subprocess.run(["git", "-C", e["path"], "status", "--porcelain", "-uno"], capture_output=True).returncode == 0
    dropped = [e for e in ov["entries"] if not (os.path.exists(e["path"]) and healthy(e))]
    for e in dropped:
        print(f"  dropped: {e['entry_id']}  {e['path'].replace(WS + '/', '')}")
    ov["entries"] = [e for e in ov["entries"] if e not in dropped] + added
    ov["observed_at"] = time.strftime("%Y-%m-%d")
    json.dump(ov, open(OVERLAY, "w"), indent=2)
    open(OVERLAY, "a").write("\n")
    print(f"wrote {len(ov['entries'])} entries")


if __name__ == "__main__":
    main()
